### ISSUE TITLE
Update documentation for 0.25.0

### ISSUE THREAD

**Issue by G3zz** [adevinta/zoe#12]
Hi, I think the documentation could be updated to mention the new features in `0.25.0`. They are really useful! 

I've taken a stab at it, please see the attached patch.
[zoe-docs-patch.txt](https://github.com/adevinta/zoe/files/5035486/zoe-docs-patch.txt)

Thanks,
Geraint

**Comment by G3zz** [comment]
I would have made a PR but don't seem to have permission

**Comment by wlezzar** [comment]
Thanks a lot @G3zz for the patch, I apply it on the repo : ) . 

In order to make a PR, you need to fork the repo and create a PR from it like [described here](https://gist.github.com/MarcDiethelm/7303312#how-to-make-a-clean-pull-request).

**Comment by wlezzar** [comment]
I just opened a PR here @G3zz : ) . Do not hesitate to comment or to approve if everything looks good
