### ISSUE TITLE
[Feature Request] Set Rentention and Cleanup Policy When Creating Topics

### ISSUE THREAD

**Issue by rsaltrelli** [adevinta/zoe#7]
```
zoe topics create --partitions 6 --replication-factor 3 --retention-ms -1 --cleanup-policy compact MyNewTopic
```

I'd love to be able to do something like this when creating a new topic.

**Comment by wlezzar** [comment]
Hi @rsaltrelli. Thanks for the issue : )

Indeed, it's a useful feature to have. I just opened a PR in this regard here: https://github.com/adevinta/zoe/pull/8 

Can you check the example and give me a feedback if this is what you needed?

**Comment by rsaltrelli** [comment]
Looks good to me. Thank you!

**Comment by wlezzar** [comment]
You're welcome!
